# Generated by Django 3.2.9 on 2021-12-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_auto_20211228_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscriber',
            new_name='subscribers',
        ),
        migrations.AddField(
            model_name='author',
            name='max_post',
            field=models.IntegerField(default=0),
        ),
    ]
